# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160802_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='pomodoro_big_rest',
            field=models.DurationField(default=datetime.timedelta(0, 900)),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='pomodoro_rest',
            field=models.DurationField(default=datetime.timedelta(0, 300)),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='pomodoro_session_count',
            field=models.IntegerField(default=4),
        ),
    ]
