# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160811_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('total_pomodoros', models.IntegerField(default=0, editable=False)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TelegramUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
