# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160811_0833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('telegram_user', 'name')]),
        ),
    ]
