# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160811_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
