# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_telegramuser_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0, 1500))),
                ('status', models.CharField(choices=[('started', 'Started'), ('finished', 'Finished'), ('unfinished', 'Unfinished')], db_index=True, default='started', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='total_rest',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='rest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AddField(
            model_name='rest',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TelegramUser'),
        ),
    ]
