# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20170115_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('all', 'All')], db_index=True, default='all', max_length=50, verbose_name='Category')),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('sent', 'Sent'), ('error', 'Error')], db_index=True, default='sending', max_length=50, verbose_name='Status')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
