# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_messagesender'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=255),
        ),
    ]
