# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_telegramuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(upload_to='audio')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Music for programming')], db_index=True, max_length=100)),
                ('audio_id', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
