# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
