# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_telegramuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
